[build-system]
requires = [
    "hatchling"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_logging"
version = "0.1.3"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, pennyeach (logging module)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pip>=23.1.2",
    "pypomes_core>=0.1.4",
    "python-dateutil>=2.8.2",
    "setuptools>=68.0.0",
    "wheel>=0.40.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Logging"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Logging/issues"
