[tool.poetry]
name = "Pylinefinder"
version = "0.1.5"
description = ""
authors = ["Antonio <antoniofernandodj@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
