[tool.poetry]
name = "rin-proj1"
version = "0.1.2"
description =""
authors = ["Harine <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"
typer = "^0.9.0"

[tool.poetry.scripts]
rin_pj1 = "rin_proj1.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
