[tool.poetry]
name = "bike"
version = "0.3.5"
description = "A lightweight model validator for modern projects."
authors = ["Manasses Lima <manasseslima@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/manasseslima/bike"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
tox = "^4.5.1"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
