[project]
name = "LordPath"
version = "2023.7.9"
description = "File Manager Helping Module base on Pathlib"
readme = "README.rst"
requires-python = ">=3.10"
keywords = []
classifiers = []
dependencies = [ "regex", "pyyaml", "LordUtils",]
[[project.authors]]
email = "lordibex@protonmail.com"
name = "lordbex"

[[project.maintainers]]
email = "lordibex@protonmail.com"
name = "lordbex"

[project.urls]
homepage = "https://github.com/LordBex"
repository = "https://github.com/LordBex"
