[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "phanos"
version = "0.0.5"
authors = [
  { name="Miroslav BuliÄka", email="bulickamiroslav@gmail.com" },
]
description = "Python client to gather data for Prometheus logging in server with multiple instances and workers."
readme = "README.md"
requires-python = ">=3.10.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/kajotgames/phanos"
"Bug Tracker" = "https://github.com/kajotgames/phanos/issues"