[project]
name = "nonebot-plugin-herocard"
version = "1.0.5"
description = "ç”¨äºæå–æœ¬å­ğŸ¥µæ ‡é¢˜å…³é”®è¯çš„ NoneBot2 æ’ä»¶"
authors = [
    { name = "Xie-Tiao", email = "1183004468@qq.com" },
]
license = "MIT"
dependencies = [
    "nonebot2>=2.0.0b2",
    "nonebot-adapter-onebot>=2.0.0b1",
]
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/Xie-Tiao/nonebot_plugin_herocard"
Repository = "https://github.com/Xie-Tiao/nonebot_plugin_herocard"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
