[tool.poetry]
name = "curcheck-manager"
version = "1.0.3"
description = "Managing curcheck projects"
authors = ["BulatXam <Khamdbulat@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
pydantic=">=1.10.4"
click=">=8.1.3"
cookiecutter=">=2.1.1"
curcheck=">=1.1.4"
changecode=">=0.0.1"
loguru=">=0.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
curcheck = 'curcheck_manager.app:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
