[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TheSilent"
version = "0.0.398"
authors = [
  { name="Michael Mueller", email="michael.j.mueller.pro@gmail.com" },
]
description = "Python penetration testing, osint, and digital forensics multi tool!"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "sqlmap"
    ]

[project.urls]
"Homepage" = "https://github.com/Invizabel/The-Silent"
"Bug Tracker" = "https://github.com/Invizabel/The-Silent/issues"
