[tool.poetry]
name = "collei"
version = "1.0.1"
description = "ğŸ‚ An unofficial Waifu.pics API wrapper for Python"
license = "MIT"
authors = ["elaresai <elaresai@gmail.com>"]
maintainers = ["elaresai <elaresai@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/elaresai/collei"
repository = "https://github.com/elaresai/collei"
classifiers = [
    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",

    "Topic :: Software Development :: Libraries",
]
packages = [{ include = "collei", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.12"
attrs = "^23.1.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
