[project]
name = "golfy"
requires-python = ">=3.7"
authors = [ {name="Alex Rubinsteyn", email="alex.rubinsteyn@unc.edu" } ]
description = "Heuristic peptide pool optimization for ELISpot and other immunological assays"
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    'Environment :: Console',
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: Apache Software License',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
]
readme = "README.md"
version = "1.5.0"  

[tool.setuptools]
packages = ["golfy"]

[project.urls]
"Homepage" = "https://github.com/pirl-unc/golfy"
"Bug Tracker" = "https://github.com/pirl-unc/golfy"