[tool.poetry]
name = "task2a"
version = "1.0.7"
description = ""
authors = ["Bill.Avramenko <billavramenko@gmail.com>"]
readme = "README.md"
packages = [{include = "pwgen"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
questionary = "^1.10.0"

[tool.poetry.scripts]
pwgen = "pwgen:pwgen_cli"
pwgen_showcase = "pwgen.showcase:pwgen_showcase"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
