[tool.poetry]
name = "dataclass-codec"
version = "0.5.5"
description = ""
authors = ["lucas.silva <lucas.silva@jeaholding.com.br>"]
readme = "README.md"
packages = [{include = "dataclass_codec", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
pre-commit = "^3.3.3"
autoflake = "^2.1.1"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
strict_optional = true
strict = true

[tool.black]
line-length = 79
