[tool.poetry]
name = "changecode"
version = "0.0.2"
description = "Change python code"
authors = ["BulatXam <Khamdbulat@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
