[tool.commitizen]
name = "cz_conventional_commits"
version = "4.0.1"
tag_format = "$version"
version_files = [
    "pyproject.toml",
]

[tool.pdm]
source = [
    { url = "https://pypi.org/simple", verify_ssl = true, name = "pypi" },
]

[tool.pdm.dev-dependencies]
dev = [
    "mypy",
    "flake8",
    "commitizen",
    "pre-commit",
    "matplotlib",
    "twine",
    "pytest>=7.3.2",
    "pytest-benchmark>=4.0.1",
]

[tool.mypy]
mypy_path = "typings"

[project]
name = "ReplayTables-andnp"
version = "4.0.1"
description = "A simple replay buffer implementation in python for sampling n-step trajectories"
authors = [
    { name = "Andy Patterson", email = "andnpatterson@gmail.com" },
]
dependencies = [
    "numba>=0.57",
    "numpy>=1.23.5",
    "scipy>=1.9.3",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"
