[build-system]
requires = ["setuptools>=61.0", "requests>=2.31.0", "beautifulsoup4>= 4.12.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mostpopularnewscnn"
version = "0.0.3"
authors = [
  { name="Tri Prasetyo Kusumo Aji", email="ajikprasetyo22@gmail.com" },
]
description = "This package will get the most popular news in CNN Indonesia"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]

[project.urls]
"Homepage" = "https://github.com/jetkesuma/most-popular-news-cnn-id"
"Medium" = "https://medium.com/@kusumo999666"
